.TH RMOL 3 "Revenue Management Optimisation Library" "RMOL Team" \" -*- nroff -*-
.SH NAME
rmol - Revenue Management Optimisation Library
.SH SYNOPSIS
#include <rmol/...>
.SH DESCRIPTION
The Revenue Management Optimisation Library (RMOL) is a collection of
routines for revenue management calculations.  The routines are written from
scratch by the RMOL team in C++, and present a modern Applications
Programming Interface (API) for C/C++ programmers, allowing wrappers to be
written for very high level languages.
.PP
The library covers the following areas,
.TP
.nf
.BR
Forecast
Single Resource Optimisation
Multiple Resource (Network / O&D) Optimisation
Overbooking
.fi
.PP
For more information please consult the RMOL Reference Manual, which is
available as an info file.  You can read it online using the shell
command 
.B info rmol-ref 
(if the library is installed).
.PP
Please report any bugs to 
.B https://sourceforge.net/tracker/?group_id=177703&atid=882290.
