# Define the substitutes for the variables present in the develpment
# support files. Note that PACKAGE, PACKAGE_NAME and PACKAGE_VERSION
# are defined in the main CMakeLists.txt (of the top root directory).
set (prefix        ${CMAKE_INSTALL_PREFIX})
set (exec_prefix   ${prefix})
set (bindir        ${exec_prefix}/bin)
set (libdir        ${exec_prefix}/${LIBDIR})
set (libexecdir    ${exec_prefix}/libexec)
set (sbindir       ${exec_prefix}/sbin)
set (sysconfdir    ${prefix}/etc)
set (includedir    ${prefix}/include)
set (datarootdir   ${prefix}/share)
set (datadir       ${datarootdir})
set (pkgdatadir    ${datarootdir}/${PACKAGE})
set (sampledir     ${datarootdir}/${PACKAGE}/samples)
set (docdir        ${datarootdir}/doc/${PACKAGE}-${PACKAGE_VERSION})
set (htmldir       ${docdir})
set (mandir        ${datarootdir}/man)
set (infodir       ${datarootdir}/info)
set (pkgincludedir ${includedir}/stdair)
set (pkglibdir     ${libdir}/stdair)
set (pkglibexecdir ${libexecdir}/stdair)
