.TH RMOL 1 "10 February 2007"
.SH NAME
rmol-config - script to get version number and compiler flags of the installed RMOL library
.SH SYNOPSIS
.B rmol-config
[\-\-prefix]  [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.PP
\fIrmol-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIRMOL\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIRMOL\fP.
.
.SH OPTIONS
.l
\fIrmol-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIRMOL\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIRMOL\fP program, with cblas
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIRMOL\fP program.
.TP 8
.B  \-\-prefix
Show the RMOL installation prefix.
.SH SEE ALSO
.BR gtk-config (1),
.BR gnome-config (1)
.SH COPYRIGHT
Copyright \(co  2007 Denis Arnaud

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
