bom_h_sources = \
		$(top_srcdir)/stdair/bom/BomSource.hpp \
		$(top_srcdir)/stdair/bom/BomTypes.hpp \
		$(top_srcdir)/stdair/bom/BomStructure.hpp \
		$(top_srcdir)/stdair/bom/BomContent.hpp \
		$(top_srcdir)/stdair/bom/BomKey.hpp \
		$(top_srcdir)/stdair/bom/BomChildrenHolder.hpp \
		$(top_srcdir)/stdair/bom/BomManager.hpp \
		$(top_srcdir)/stdair/bom/Structure.hpp \
		$(top_srcdir)/stdair/bom/BomChildrenHolderImp.hpp \
		$(top_srcdir)/stdair/bom/BomList.hpp \
		$(top_srcdir)/stdair/bom/BomMap.hpp \
		$(top_srcdir)/stdair/bom/BomMultimap.hpp \
		$(top_srcdir)/stdair/bom/BomIterator.hpp \
		$(top_srcdir)/stdair/bom/BomRootKey.hpp \
		$(top_srcdir)/stdair/bom/YieldStoreKey.hpp \
		$(top_srcdir)/stdair/bom/InventoryKey.hpp \
		$(top_srcdir)/stdair/bom/FlightDateKey.hpp \
		$(top_srcdir)/stdair/bom/LegDateKey.hpp \
		$(top_srcdir)/stdair/bom/LegCabinKey.hpp \
		$(top_srcdir)/stdair/bom/SegmentDateKey.hpp \
		$(top_srcdir)/stdair/bom/SegmentCabinKey.hpp \
		$(top_srcdir)/stdair/bom/BookingClassKey.hpp \
		$(top_srcdir)/stdair/bom/BucketKey.hpp \
		$(top_srcdir)/stdair/bom/FlightPeriodKey.hpp \
		$(top_srcdir)/stdair/bom/SegmentPeriodKey.hpp \
		$(top_srcdir)/stdair/bom/ReachableUniverseKey.hpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSetKey.hpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriodKey.hpp \
		$(top_srcdir)/stdair/bom/NetworkKey.hpp \
		$(top_srcdir)/stdair/bom/NetworkDateKey.hpp \
		$(top_srcdir)/stdair/bom/AirportDateKey.hpp \
		$(top_srcdir)/stdair/bom/OutboundPathKey.hpp \
		$(top_srcdir)/stdair/bom/AirlineFeatureKey.hpp \
		$(top_srcdir)/stdair/bom/DemandStreamKey.hpp \
		$(top_srcdir)/stdair/bom/BomRootTypes.hpp \
		$(top_srcdir)/stdair/bom/InventoryTypes.hpp \
		$(top_srcdir)/stdair/bom/FlightDateTypes.hpp \
		$(top_srcdir)/stdair/bom/SegmentDateTypes.hpp \
		$(top_srcdir)/stdair/bom/LegDateTypes.hpp \
		$(top_srcdir)/stdair/bom/SegmentCabinTypes.hpp \
		$(top_srcdir)/stdair/bom/LegCabinTypes.hpp \
		$(top_srcdir)/stdair/bom/BookingClassTypes.hpp \
		$(top_srcdir)/stdair/bom/BucketTypes.hpp \
		$(top_srcdir)/stdair/bom/FlightPeriodTypes.hpp \
		$(top_srcdir)/stdair/bom/SegmentPeriodTypes.hpp \
		$(top_srcdir)/stdair/bom/ReachableUniverseTypes.hpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSetTypes.hpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriodTypes.hpp \
		$(top_srcdir)/stdair/bom/NetworkTypes.hpp \
		$(top_srcdir)/stdair/bom/NetworkDateTypes.hpp \
		$(top_srcdir)/stdair/bom/AirportDateTypes.hpp \
		$(top_srcdir)/stdair/bom/OutboundPathTypes.hpp \
		$(top_srcdir)/stdair/bom/AirlineFeatureTypes.hpp \
		$(top_srcdir)/stdair/bom/TravelSolutionTypes.hpp \
		$(top_srcdir)/stdair/bom/DemandStreamTypes.hpp \
		$(top_srcdir)/stdair/bom/EventTypes.hpp \
		$(top_srcdir)/stdair/bom/YieldStoreTypes.hpp \
		$(top_srcdir)/stdair/bom/BomRootContent.hpp \
		$(top_srcdir)/stdair/bom/InventoryContent.hpp \
		$(top_srcdir)/stdair/bom/FlightDateContent.hpp \
		$(top_srcdir)/stdair/bom/SegmentDateContent.hpp \
		$(top_srcdir)/stdair/bom/LegDateContent.hpp \
		$(top_srcdir)/stdair/bom/SegmentCabinContent.hpp \
		$(top_srcdir)/stdair/bom/LegCabinContent.hpp \
		$(top_srcdir)/stdair/bom/BookingClassContent.hpp \
		$(top_srcdir)/stdair/bom/BucketContent.hpp \
		$(top_srcdir)/stdair/bom/FlightPeriodContent.hpp \
		$(top_srcdir)/stdair/bom/SegmentPeriodContent.hpp \
		$(top_srcdir)/stdair/bom/ReachableUniverseContent.hpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSetContent.hpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriodContent.hpp \
		$(top_srcdir)/stdair/bom/NetworkContent.hpp \
		$(top_srcdir)/stdair/bom/NetworkDateContent.hpp \
		$(top_srcdir)/stdair/bom/AirportDateContent.hpp \
		$(top_srcdir)/stdair/bom/OutboundPathContent.hpp \
		$(top_srcdir)/stdair/bom/AirlineFeatureContent.hpp \
		$(top_srcdir)/stdair/bom/DemandStreamContent.hpp \
		$(top_srcdir)/stdair/bom/YieldStoreContent.hpp \
		$(top_srcdir)/stdair/bom/BomRoot.hpp \
		$(top_srcdir)/stdair/bom/Inventory.hpp \
		$(top_srcdir)/stdair/bom/FlightDate.hpp \
		$(top_srcdir)/stdair/bom/SegmentDate.hpp \
		$(top_srcdir)/stdair/bom/LegDate.hpp \
		$(top_srcdir)/stdair/bom/SegmentCabin.hpp \
		$(top_srcdir)/stdair/bom/LegCabin.hpp \
		$(top_srcdir)/stdair/bom/BookingClass.hpp \
		$(top_srcdir)/stdair/bom/Bucket.hpp \
		$(top_srcdir)/stdair/bom/FlightPeriod.hpp \
		$(top_srcdir)/stdair/bom/SegmentPeriod.hpp \
		$(top_srcdir)/stdair/bom/ReachableUniverse.hpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSet.hpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriod.hpp \
		$(top_srcdir)/stdair/bom/Network.hpp \
		$(top_srcdir)/stdair/bom/NetworkDate.hpp \
		$(top_srcdir)/stdair/bom/AirportDate.hpp \
		$(top_srcdir)/stdair/bom/OutboundPath.hpp \
		$(top_srcdir)/stdair/bom/AirlineFeature.hpp \
		$(top_srcdir)/stdair/bom/DemandStream.hpp \
		$(top_srcdir)/stdair/bom/YieldStore.hpp \
		$(top_srcdir)/stdair/bom/OptimizerStruct.hpp \
		$(top_srcdir)/stdair/bom/DoWStruct.hpp \
		$(top_srcdir)/stdair/bom/TravelSolutionStruct.hpp \
		$(top_srcdir)/stdair/bom/BookingRequestStruct.hpp \
		$(top_srcdir)/stdair/bom/AirlineStruct.hpp \
		$(top_srcdir)/stdair/bom/EventStruct.hpp \
		$(top_srcdir)/stdair/bom/EventQueue.hpp
bom_cc_sources = \
		$(top_srcdir)/stdair/bom/BomManager.cpp \
		$(top_srcdir)/stdair/bom/BomRootKey.cpp \
		$(top_srcdir)/stdair/bom/YieldStoreKey.cpp \
		$(top_srcdir)/stdair/bom/InventoryKey.cpp \
		$(top_srcdir)/stdair/bom/FlightDateKey.cpp \
		$(top_srcdir)/stdair/bom/LegDateKey.cpp \
		$(top_srcdir)/stdair/bom/LegCabinKey.cpp \
		$(top_srcdir)/stdair/bom/SegmentDateKey.cpp \
		$(top_srcdir)/stdair/bom/SegmentCabinKey.cpp \
		$(top_srcdir)/stdair/bom/BookingClassKey.cpp \
		$(top_srcdir)/stdair/bom/BucketKey.cpp \
		$(top_srcdir)/stdair/bom/FlightPeriodKey.cpp \
		$(top_srcdir)/stdair/bom/SegmentPeriodKey.cpp \
		$(top_srcdir)/stdair/bom/ReachableUniverseKey.cpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSetKey.cpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriodKey.cpp \
		$(top_srcdir)/stdair/bom/NetworkKey.cpp \
		$(top_srcdir)/stdair/bom/NetworkDateKey.cpp \
		$(top_srcdir)/stdair/bom/AirportDateKey.cpp \
		$(top_srcdir)/stdair/bom/OutboundPathKey.cpp \
		$(top_srcdir)/stdair/bom/AirlineFeatureKey.cpp \
		$(top_srcdir)/stdair/bom/DemandStreamKey.cpp \
		$(top_srcdir)/stdair/bom/BomRootContent.cpp \
		$(top_srcdir)/stdair/bom/InventoryContent.cpp \
		$(top_srcdir)/stdair/bom/FlightDateContent.cpp \
		$(top_srcdir)/stdair/bom/SegmentDateContent.cpp \
		$(top_srcdir)/stdair/bom/LegDateContent.cpp \
		$(top_srcdir)/stdair/bom/SegmentCabinContent.cpp \
		$(top_srcdir)/stdair/bom/LegCabinContent.cpp \
		$(top_srcdir)/stdair/bom/BookingClassContent.cpp \
		$(top_srcdir)/stdair/bom/BucketContent.cpp \
		$(top_srcdir)/stdair/bom/FlightPeriodContent.cpp \
		$(top_srcdir)/stdair/bom/SegmentPeriodContent.cpp \
		$(top_srcdir)/stdair/bom/ReachableUniverseContent.cpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSetContent.cpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriodContent.cpp \
		$(top_srcdir)/stdair/bom/NetworkContent.cpp \
		$(top_srcdir)/stdair/bom/NetworkDateContent.cpp \
		$(top_srcdir)/stdair/bom/AirportDateContent.cpp \
		$(top_srcdir)/stdair/bom/OutboundPathContent.cpp \
		$(top_srcdir)/stdair/bom/AirlineFeatureContent.cpp \
		$(top_srcdir)/stdair/bom/DemandStreamContent.cpp \
		$(top_srcdir)/stdair/bom/YieldStoreContent.cpp \
		$(top_srcdir)/stdair/bom/BomRoot.cpp \
		$(top_srcdir)/stdair/bom/Inventory.cpp \
		$(top_srcdir)/stdair/bom/FlightDate.cpp \
		$(top_srcdir)/stdair/bom/SegmentDate.cpp \
		$(top_srcdir)/stdair/bom/LegDate.cpp \
		$(top_srcdir)/stdair/bom/SegmentCabin.cpp \
		$(top_srcdir)/stdair/bom/LegCabin.cpp \
		$(top_srcdir)/stdair/bom/BookingClass.cpp \
		$(top_srcdir)/stdair/bom/Bucket.cpp \
		$(top_srcdir)/stdair/bom/FlightPeriod.cpp \
		$(top_srcdir)/stdair/bom/SegmentPeriod.cpp \
		$(top_srcdir)/stdair/bom/ReachableUniverse.cpp \
		$(top_srcdir)/stdair/bom/OriginDestinationSet.cpp \
		$(top_srcdir)/stdair/bom/SegmentPathPeriod.cpp \
		$(top_srcdir)/stdair/bom/Network.cpp \
		$(top_srcdir)/stdair/bom/NetworkDate.cpp \
		$(top_srcdir)/stdair/bom/AirportDate.cpp \
		$(top_srcdir)/stdair/bom/OutboundPath.cpp \
		$(top_srcdir)/stdair/bom/AirlineFeature.cpp \
		$(top_srcdir)/stdair/bom/DemandStream.cpp \
		$(top_srcdir)/stdair/bom/YieldStore.cpp \
		$(top_srcdir)/stdair/bom/OptimizerStruct.cpp \
		$(top_srcdir)/stdair/bom/DoWStruct.cpp \
		$(top_srcdir)/stdair/bom/TravelSolutionStruct.cpp \
		$(top_srcdir)/stdair/bom/BookingRequestStruct.cpp \
		$(top_srcdir)/stdair/bom/AirlineStruct.cpp \
		$(top_srcdir)/stdair/bom/EventStruct.cpp \
		$(top_srcdir)/stdair/bom/EventQueue.cpp