.TH LATUS 3 "Leisure And Travel Usage Simulation" "Amadeus - MIT" \" -*- nroff -*-
.SH NAME
latus - Leisure And Travel Usage Simulation
.SH SYNOPSIS
#include <latus/...>
.SH DESCRIPTION
LATUS is a Demand Simulator for Travel and Leisure oriented Users.
It uses dynamic libraries for the modules, so as to be flexible in the
implementation of new methods and algorithms for each of those modules.
 The modules are typically:
 * Demand Generator (latus)
 * User Choice Model (UCM)
 * Central Reservation System (CRS)
 * Travel Solutions Provider (TSP)
 * Availability Server (AVS)
 * Inventory (INV)
 * Revenue Management System (RMS). 

The providers (represented by an Inventory and a Revenue Management System) 
can be of any type (airline, hotel, car rental, cruise, insurance companies, 
etc.).

Install the latus package if you need a program to simulate how different
algorithms and methods best react to given demand scenarios.
.PP
The program covers the following areas,
.TP
.nf
.BR
Demand Generation
Central Reservation System (CRS)
User Choice Model (UCM)
Central Reservation System (CRS)
Travel Solutions Provider (TSP)
Availability Server (AVS)
Inventory (INV)
Revenue Management System (RMS). 
.fi
.PP
For more information please consult the LATUS Reference Manual, which is
available as an info file.  You can read it online using the shell
command 
.B info latus-ref 
(if the library is installed).
.PP
Please report any bugs to 
.B dev-ori@amadeus.com
