.TH StdAir 3 "C++ Standard Airline IT Object Library" "StdAir Team" \" -*- nroff -*-
.SH NAME
stdair - C++ Standard Airline IT Object Library
.SH SYNOPSIS
#include <stdair/...>
.SH DESCRIPTION
The Standard Airline IT (STDAIR) library is a collection of routines
for travel market simulation. The routines are written from scratch by
the StdAir team in C++, and present a modern Applications Programming
Interface (API) for C/C++ programmers, allowing wrappers to be written
for very high level languages.
.PP
The library covers the following areas,
.TP
.nf
.BR
Architecture
.fi
.PP
Please report any bugs to 
.B https://sourceforge.net/apps/trac/stdair/report
