combom_h_sources = $(top_srcdir)/latus/com/bom/BomAbstract.hpp \
					$(top_srcdir)/latus/com/bom/KeyAbstract.hpp \
					$(top_srcdir)/latus/com/bom/StructAbstract.hpp \
					$(top_srcdir)/latus/com/bom/DistributionDetails.hpp \
					$(top_srcdir)/latus/com/bom/ClassPathList.hpp \
					$(top_srcdir)/latus/com/bom/CityPairDateList.hpp \
					$(top_srcdir)/latus/com/bom/ClassPathDistributionList.hpp \
					$(top_srcdir)/latus/com/bom/DepDateDistributionList.hpp \
					$(top_srcdir)/latus/com/bom/Event.hpp \
					$(top_srcdir)/latus/com/bom/BookingDay.hpp \
					$(top_srcdir)/latus/com/bom/CityPairKey.hpp \
					$(top_srcdir)/latus/com/bom/CityPairList.hpp \
					$(top_srcdir)/latus/com/bom/CityPair.hpp \
					$(top_srcdir)/latus/com/bom/CityPairDate.hpp \
					$(top_srcdir)/latus/com/bom/ClassPath.hpp \
					$(top_srcdir)/latus/com/bom/PeriodKey.hpp \
					$(top_srcdir)/latus/com/bom/FlightKey.hpp \
					$(top_srcdir)/latus/com/bom/FlightPeriodKey.hpp \
					$(top_srcdir)/latus/com/bom/LegPeriodKey.hpp \
					$(top_srcdir)/latus/com/bom/AirportPairKey.hpp \
					$(top_srcdir)/latus/com/bom/SegmentPeriodKey.hpp \
					$(top_srcdir)/latus/com/bom/InventoryKey.hpp \
					$(top_srcdir)/latus/com/bom/FlightDateKey.hpp \
					$(top_srcdir)/latus/com/bom/LegDateKey.hpp \
					$(top_srcdir)/latus/com/bom/LegCabinKey.hpp \
					$(top_srcdir)/latus/com/bom/SegmentDateKey.hpp \
					$(top_srcdir)/latus/com/bom/SegmentCabinKey.hpp \
					$(top_srcdir)/latus/com/bom/ClassKey.hpp \
					$(top_srcdir)/latus/com/bom/NetworkDateKey.hpp \
					$(top_srcdir)/latus/com/bom/AirportDateKey.hpp \
					$(top_srcdir)/latus/com/bom/OutboundPathKey.hpp \
					$(top_srcdir)/latus/com/bom/TravelSolution.hpp \
					$(top_srcdir)/latus/com/bom/WorldSchedule.hpp \
					$(top_srcdir)/latus/com/bom/InventoryList.hpp \
					$(top_srcdir)/latus/com/bom/Inventory.hpp \
					$(top_srcdir)/latus/com/bom/Network.hpp \
					$(top_srcdir)/latus/com/bom/NetworkDateList.hpp \
					$(top_srcdir)/latus/com/bom/NetworkDate.hpp \
					$(top_srcdir)/latus/com/bom/AirportDateList.hpp \
					$(top_srcdir)/latus/com/bom/AirportDate.hpp \
					$(top_srcdir)/latus/com/bom/OutboundPathList.hpp \
					$(top_srcdir)/latus/com/bom/OutboundPath.hpp \
					$(top_srcdir)/latus/com/bom/FlightPeriod.hpp \
					$(top_srcdir)/latus/com/bom/LegPeriodList.hpp \
					$(top_srcdir)/latus/com/bom/LegPeriod.hpp \
					$(top_srcdir)/latus/com/bom/SegmentPeriodList.hpp \
					$(top_srcdir)/latus/com/bom/SegmentPeriod.hpp \
					$(top_srcdir)/latus/com/bom/FlightDateList.hpp \
					$(top_srcdir)/latus/com/bom/FlightDate.hpp \
					$(top_srcdir)/latus/com/bom/LegDateList.hpp \
					$(top_srcdir)/latus/com/bom/LegDate.hpp \
					$(top_srcdir)/latus/com/bom/LegCabinList.hpp \
					$(top_srcdir)/latus/com/bom/LegCabin.hpp \
					$(top_srcdir)/latus/com/bom/SegmentDateList.hpp \
					$(top_srcdir)/latus/com/bom/SegmentDate.hpp \
					$(top_srcdir)/latus/com/bom/SegmentCabinList.hpp \
					$(top_srcdir)/latus/com/bom/SegmentCabin.hpp \
					$(top_srcdir)/latus/com/bom/ClassStruct.hpp
combom_cc_sources = $(top_srcdir)/latus/com/bom/BookingDay.cpp \
					$(top_srcdir)/latus/com/bom/CityPairKey.cpp \
					$(top_srcdir)/latus/com/bom/CityPair.cpp \
					$(top_srcdir)/latus/com/bom/CityPairDate.cpp \
					$(top_srcdir)/latus/com/bom/ClassPath.cpp \
					$(top_srcdir)/latus/com/bom/PeriodKey.cpp \
					$(top_srcdir)/latus/com/bom/FlightKey.cpp \
					$(top_srcdir)/latus/com/bom/FlightPeriodKey.cpp \
					$(top_srcdir)/latus/com/bom/LegPeriodKey.cpp \
					$(top_srcdir)/latus/com/bom/AirportPairKey.cpp \
					$(top_srcdir)/latus/com/bom/SegmentPeriodKey.cpp \
					$(top_srcdir)/latus/com/bom/InventoryKey.cpp \
					$(top_srcdir)/latus/com/bom/FlightDateKey.cpp \
					$(top_srcdir)/latus/com/bom/LegDateKey.cpp \
					$(top_srcdir)/latus/com/bom/LegCabinKey.cpp \
					$(top_srcdir)/latus/com/bom/SegmentDateKey.cpp \
					$(top_srcdir)/latus/com/bom/SegmentCabinKey.cpp \
					$(top_srcdir)/latus/com/bom/ClassKey.cpp \
					$(top_srcdir)/latus/com/bom/NetworkDateKey.cpp \
					$(top_srcdir)/latus/com/bom/AirportDateKey.cpp \
					$(top_srcdir)/latus/com/bom/OutboundPathKey.cpp \
					$(top_srcdir)/latus/com/bom/WorldSchedule.cpp \
					$(top_srcdir)/latus/com/bom/Inventory.cpp \
					$(top_srcdir)/latus/com/bom/Network.cpp \
					$(top_srcdir)/latus/com/bom/NetworkDate.cpp \
					$(top_srcdir)/latus/com/bom/AirportDate.cpp \
					$(top_srcdir)/latus/com/bom/OutboundPath.cpp \
					$(top_srcdir)/latus/com/bom/FlightPeriod.cpp \
					$(top_srcdir)/latus/com/bom/LegPeriod.cpp \
					$(top_srcdir)/latus/com/bom/SegmentPeriod.cpp \
					$(top_srcdir)/latus/com/bom/FlightDate.cpp \
					$(top_srcdir)/latus/com/bom/LegDate.cpp \
					$(top_srcdir)/latus/com/bom/LegCabin.cpp \
					$(top_srcdir)/latus/com/bom/SegmentDate.cpp \
					$(top_srcdir)/latus/com/bom/SegmentCabin.cpp \
					$(top_srcdir)/latus/com/bom/ClassStruct.cpp
